on:
  #schedule:
    # every thursday at 6 pm in december
    #- cron: '0 16 * 12 4'
  workflow_dispatch:

name: Deploy app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rsconnect", "shiny", "pak"))'
          # falls du mehr Pakete brauchst, hier ergänzen
          # oder eine DESCRIPTION-Datei nutzen: pak::pak()

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_USER: ${{ secrets.SHINYAPPS_USER }}
        run: |
          Rscript -e 'library(rsconnect); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_USER"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appDir=".", appName="rfl-tools")'
